#开发环境配置

server:
  # 服务端口
  port: 10100


spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    username: ${MYSQL_USER:alice}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/lin_cms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF8
  flyway:
    enabled: true
    table: flyway_schema_history
    baseline-on-migrate: true
    locations: classpath:db/migration

# 开启权限拦截
auth:
  enabled: true

# 开启登录要求验证码
login-captcha:
  enabled: false
  secret: "m49CPM5ak@MDXTzbbT_ZEyMM3KBsBn!h"

# 开启http请求日志记录
request-log:
  enabled: true


logging:
  level:
    # web信息日志记录
    web: debug
    # SQL日志记录
    io.github.talelin.latticy.mapper: debug




