version: '3.9'

services:
  cms-java:
    image: crpi-gjiqcc10v58u83a9.cn-hangzhou.personal.cr.aliyuncs.com/qtcms/qt-cms:${CMS_JAVA_VERSION}
    ports:
      - "10200:10100"
    environment:
      - MYSQL_HOST=db_mysql
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SERVICE_ENVIRONMENT=${SERVICE_ENVIRONMENT}
    depends_on:
      db_mysql:
        condition: service_healthy
    restart: always
    networks:
      cms-system:

  cms-vue:
    image: crpi-gjiqcc10v58u83a9.cn-hangzhou.personal.cr.aliyuncs.com/qtcms/qt-cms-vue:${CMS_VUE_VERSION}
    ports:
      - "8080:80"
    networks:
      cms-system:

  db_mysql:
    image: mysql:latest
    ports:
      - "13306:3306"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=lin_cms
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u ${MYSQL_USER} --password=${MYSQL_PASSWORD}" ]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      cms-system:
networks:
  cms-system: